-- phpMyAdmin SQL Dump
-- version 5.2.1
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1:3306
-- Generation Time: Jul 11, 2025 at 05:26 AM
-- Server version: 9.1.0
-- PHP Version: 7.4.33

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `farm_world_crm`
--

-- --------------------------------------------------------

--
-- Table structure for table `tblemailtemplates`
--

DROP TABLE IF EXISTS `tblemailtemplates`;
CREATE TABLE IF NOT EXISTS `tblemailtemplates` (
  `emailtemplateid` int NOT NULL AUTO_INCREMENT,
  `type` longtext COLLATE utf8mb4_unicode_ci NOT NULL,
  `slug` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,
  `language` varchar(40) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `name` longtext COLLATE utf8mb4_unicode_ci NOT NULL,
  `subject` longtext COLLATE utf8mb4_unicode_ci NOT NULL,
  `message` longtext COLLATE utf8mb4_unicode_ci NOT NULL,
  `fromname` longtext COLLATE utf8mb4_unicode_ci NOT NULL,
  `fromemail` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `plaintext` int NOT NULL DEFAULT '0',
  `active` tinyint NOT NULL DEFAULT '0',
  `order` int NOT NULL,
  PRIMARY KEY (`emailtemplateid`)
) ENGINE=InnoDB AUTO_INCREMENT=154 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Dumping data for table `tblemailtemplates`
--

INSERT INTO `tblemailtemplates` (`emailtemplateid`, `type`, `slug`, `language`, `name`, `subject`, `message`, `fromname`, `fromemail`, `plaintext`, `active`, `order`) VALUES
(1, 'client', 'new-client-created', 'english', 'New Contact Added/Registered (Welcome Email)', 'Welcome aboard', 'Dear {contact_firstname} {contact_lastname}<br /><br />Thank you for registering on the <strong>{companyname}</strong> CRM System.<br /><br />We just wanted to say welcome.<br /><br />Please contact us if you need any help.<br /><br />Click here to view your profile: <a href=\"{crm_url}\">{crm_url}</a><br /><br />Kind Regards, <br />{email_signature}<br /><br />(This is an automated email, so please don\'t reply to this email address)', '{companyname}', '', 0, 1, 0),
(2, 'invoice', 'invoice-send-to-client', 'english', 'Send Invoice to Customer', 'Invoice with number {invoice_number} created', '<span style=\"font-size: 12pt;\">Dear {contact_firstname} {contact_lastname}</span><br /><br /><span style=\"font-size: 12pt;\">We have prepared the following invoice for you: <strong># {invoice_number}</strong></span><br /><br /><span style=\"font-size: 12pt;\"><strong>Invoice status</strong>: {invoice_status}</span><br /><br /><span style=\"font-size: 12pt;\">You can view the invoice on the following link: <a href=\"{invoice_link}\">{invoice_number}</a></span><br /><br /><span style=\"font-size: 12pt;\">Please contact us for more information.</span><br /><br /><span style=\"font-size: 12pt;\">Kind Regards,</span><br /><span style=\"font-size: 12pt;\">{email_signature}</span>', '{companyname}', '', 0, 1, 0),
(3, 'ticket', 'new-ticket-opened-admin', 'english', 'New Ticket Opened (Opened by Staff, Sent to Customer)', 'New Support Ticket Opened', '<span style=\"font-size: 12pt;\">Hi {contact_firstname} {contact_lastname}</span><br /><br /><span style=\"font-size: 12pt;\">New support ticket has been opened.</span><br /><br /><span style=\"font-size: 12pt;\"><strong>Subject:</strong> {ticket_subject}</span><br /><span style=\"font-size: 12pt;\"><strong>Department:</strong> {ticket_department}</span><br /><span style=\"font-size: 12pt;\"><strong>Priority:</strong> {ticket_priority}</span><br /><br /><span style=\"font-size: 12pt;\"><strong>Ticket message:</strong></span><br /><span style=\"font-size: 12pt;\">{ticket_message}</span><br /><br /><span style=\"font-size: 12pt;\">You can view the ticket on the following link: <a href=\"{ticket_url}\">#{ticket_id}<br /><br /></a>Kind Regards,</span><br /><span style=\"font-size: 12pt;\">{email_signature}</span>', '{companyname}', '', 0, 1, 0),
(4, 'ticket', 'ticket-reply', 'english', 'Ticket Reply (Sent to Customer)', 'New Ticket Reply', '<span style=\"font-size: 12pt;\">Hi {contact_firstname} {contact_lastname}</span><br /><br /><span style=\"font-size: 12pt;\">You have a new ticket reply to ticket <a href=\"{ticket_url}\">#{ticket_id}</a></span><br /><br /><span style=\"font-size: 12pt;\"><strong>Ticket Subject:</strong> {ticket_subject}<br /></span><br /><span style=\"font-size: 12pt;\"><strong>Ticket message:</strong></span><br /><span style=\"font-size: 12pt;\">{ticket_message}</span><br /><br /><span style=\"font-size: 12pt;\">You can view the ticket on the following link: <a href=\"{ticket_url}\">#{ticket_id}</a></span><br /><br /><span style=\"font-size: 12pt;\">Kind Regards,</span><br /><span style=\"font-size: 12pt;\">{email_signature}</span>', '{companyname}', '', 0, 1, 0),
(5, 'ticket', 'ticket-autoresponse', 'english', 'New Ticket Opened - Autoresponse', 'New Support Ticket Opened', '<span style=\"font-size: 12pt;\">Hi {contact_firstname} {contact_lastname}</span><br /><br /><span style=\"font-size: 12pt;\">Thank you for contacting our support team. A support ticket has now been opened for your request. You will be notified when a response is made by email.</span><br /> <br /><span style=\"font-size: 12pt;\"><strong>Subject:</strong> {ticket_subject}</span><br /><span style=\"font-size: 12pt;\"><strong>Department</strong>: {ticket_department}</span><br /><span style=\"font-size: 12pt;\"><strong>Priority:</strong> {ticket_priority}</span><br /> <br /><span style=\"font-size: 12pt;\"><strong>Ticket message:</strong></span><br /><span style=\"font-size: 12pt;\">{ticket_message}</span><br /><br /><span style=\"font-size: 12pt;\">You can view the ticket on the following link: <a href=\"{ticket_url}\">#{ticket_id}</a></span><br /> <br /><span style=\"font-size: 12pt;\">Kind Regards,</span><br /><span style=\"font-size: 12pt;\">{email_signature}</span>', '{companyname}', '', 0, 1, 0),
(6, 'invoice', 'invoice-payment-recorded', 'english', 'Invoice Payment Recorded (Sent to Customer)', 'Invoice Payment Recorded', '<span style=\"font-size: 12pt;\">Hello {contact_firstname}&nbsp;{contact_lastname}<br /><br /></span>Thank you for the payment. Find the payment details below:<br /><br />-------------------------------------------------<br /><br />Amount:&nbsp;<strong>{payment_total}<br /></strong>Date:&nbsp;<strong>{payment_date}</strong><br />Invoice number:&nbsp;<span style=\"font-size: 12pt;\"><strong># {invoice_number}<br /><br /></strong></span>-------------------------------------------------<br /><br />You can always view the invoice for this payment at the following link:&nbsp;<a href=\"{invoice_link}\"><span style=\"font-size: 12pt;\">{invoice_number}</span></a><br /><br />We are looking forward working with you.<br /><br /><span style=\"font-size: 12pt;\">Kind Regards,</span><br /><span style=\"font-size: 12pt;\">{email_signature}</span>', '{companyname}', '', 0, 1, 0),
(7, 'invoice', 'invoice-overdue-notice', 'english', 'Invoice Overdue Notice', 'Invoice Overdue Notice - {invoice_number}', '<span style=\"font-size: 12pt;\">Hi {contact_firstname} {contact_lastname}</span><br /><br /><span style=\"font-size: 12pt;\">This is an overdue notice for invoice <strong># {invoice_number}</strong></span><br /><br /><span style=\"font-size: 12pt;\">This invoice was due: {invoice_duedate}</span><br /><br /><span style=\"font-size: 12pt;\">You can view the invoice on the following link: <a href=\"{invoice_link}\">{invoice_number}</a></span><br /><br /><span style=\"font-size: 12pt;\">Kind Regards,</span><br /><span style=\"font-size: 12pt;\">{email_signature}</span>', '{companyname}', '', 0, 1, 0),
(8, 'invoice', 'invoice-already-send', 'english', 'Invoice Already Sent to Customer', 'Invoice # {invoice_number} ', '<span style=\"font-size: 12pt;\">Hi {contact_firstname} {contact_lastname}</span><br /><br /><span style=\"font-size: 12pt;\">At your request, here is the invoice with number <strong># {invoice_number}</strong></span><br /><br /><span style=\"font-size: 12pt;\">You can view the invoice on the following link: <a href=\"{invoice_link}\">{invoice_number}</a></span><br /><br /><span style=\"font-size: 12pt;\">Please contact us for more information.</span><br /><br /><span style=\"font-size: 12pt;\">Kind Regards,</span><br /><span style=\"font-size: 12pt;\">{email_signature}</span>', '{companyname}', '', 0, 1, 0),
(9, 'ticket', 'new-ticket-created-staff', 'english', 'New Ticket Created (Opened by Customer, Sent to Staff Members)', 'New Ticket Created', '<span style=\"font-size: 12pt;\">A new support ticket has been opened.</span><br /> <br /><span style=\"font-size: 12pt;\"><strong>Subject</strong>: {ticket_subject}</span><br /><span style=\"font-size: 12pt;\"><strong>Department</strong>: {ticket_department}</span><br /><span style=\"font-size: 12pt;\"><strong>Priority</strong>: {ticket_priority}</span><br /> <br /><span style=\"font-size: 12pt;\"><strong>Ticket message:</strong></span><br /><span style=\"font-size: 12pt;\">{ticket_message}</span><br /><br /><span style=\"font-size: 12pt;\">You can view the ticket on the following link: <a href=\"{ticket_url}\">#{ticket_id}<br /></a></span><br /><span style=\"font-size: 12pt;\">Kind Regards,</span><br /><span style=\"font-size: 12pt;\">{email_signature}</span>', '{companyname}', '', 0, 1, 0),
(10, 'estimate', 'estimate-send-to-client', 'english', 'Send Estimate to Customer', 'Estimate # {estimate_number} created', '<span style=\"font-size: 12pt;\">Dear {contact_firstname} {contact_lastname}</span><br /><br /><span style=\"font-size: 12pt;\">Please find the attached estimate <strong># {estimate_number}</strong></span><br /><br /><span style=\"font-size: 12pt;\"><strong>Estimate status:</strong> {estimate_status}</span><br /><br /><span style=\"font-size: 12pt;\">You can view the estimate on the following link: <a href=\"{estimate_link}\">{estimate_number}</a></span><br /><br /><br /><span style=\"font-size: 12pt;\">We look forward to your communication.</span><br /><br /><span style=\"font-size: 12pt;\">Kind Regards,</span><br /><span style=\"font-size: 12pt;\">{email_signature}<br /></span>', '{companyname}', '', 0, 1, 0),
(11, 'ticket', 'ticket-reply-to-admin', 'english', 'Ticket Reply (Sent to Staff)', 'New Support Ticket Reply', '<span style=\"font-size: 12pt;\">A new support ticket reply from {contact_firstname} {contact_lastname}</span><br /> <br /><span style=\"font-size: 12pt;\"><strong>Subject</strong>: {ticket_subject}</span><br /><span style=\"font-size: 12pt;\"><strong>Department</strong>: {ticket_department}</span><br /><span style=\"font-size: 12pt;\"><strong>Priority</strong>: {ticket_priority}</span><br /> <br /><span style=\"font-size: 12pt;\"><strong>Ticket message:</strong></span><br /><span style=\"font-size: 12pt;\">{ticket_message}</span><br /> <br /><span style=\"font-size: 12pt;\">You can view the ticket on the following link: <a href=\"{ticket_url}\">#{ticket_id}</a></span><br /> <br /><span style=\"font-size: 12pt;\">Kind Regards,</span><br /><span style=\"font-size: 12pt;\">{email_signature}</span>', '{companyname}', '', 0, 1, 0),
(12, 'estimate', 'estimate-already-send', 'english', 'Estimate Already Sent to Customer', 'Estimate # {estimate_number} ', '<span style=\"font-size: 12pt;\">Dear {contact_firstname} {contact_lastname}</span><br /> <br /><span style=\"font-size: 12pt;\">Thank you for your estimate request.</span><br /> <br /><span style=\"font-size: 12pt;\">You can view the estimate on the following link: <a href=\"{estimate_link}\">{estimate_number}</a></span><br /> <br /><span style=\"font-size: 12pt;\">Please contact us for more information.</span><br /> <br /><span style=\"font-size: 12pt;\">Kind Regards,</span><br /><span style=\"font-size: 12pt;\">{email_signature}</span>', '{companyname}', '', 0, 1, 0),
(13, 'contract', 'contract-expiration', 'english', 'Agreement Expiration Reminder (Sent to Customer Contacts)', 'Agreement Expiration Reminder', '<span style=\"font-size: 12pt;\">Dear {client_company}</span><br /><br /><span style=\"font-size: 12pt;\">This is a reminder that the following agreement will expire soon:</span><br /><br /><span style=\"font-size: 12pt;\"><strong>Subject:</strong> {agreement_subject}</span><br /><span style=\"font-size: 12pt;\"><strong>Description:</strong> {agreement_description}</span><br /><span style=\"font-size: 12pt;\"><strong>Date Start:</strong> {agreement_datestart}</span><br /><span style=\"font-size: 12pt;\"><strong>Date End:</strong> {agreement_dateend}</span><br /><br /><span style=\"font-size: 12pt;\">Please contact us for more information.</span><br /><br /><span style=\"font-size: 12pt;\">Kind Regards,</span><br /><span style=\"font-size: 12pt;\">{email_signature}</span>', '{companyname}', '', 0, 1, 0),
(14, 'tasks', 'task-assigned', 'english', 'New Task Assigned (Sent to Staff)', 'New Task Assigned to You - {task_name}', '<span style=\"font-size: 12pt;\">Dear {staff_firstname}</span><br /><br /><span style=\"font-size: 12pt;\">You have been assigned to a new task:</span><br /><br /><span style=\"font-size: 12pt;\"><strong>Name:</strong> {task_name}<br /></span><strong>Start Date:</strong> {task_startdate}<br /><span style=\"font-size: 12pt;\"><strong>Due date:</strong> {task_duedate}</span><br /><span style=\"font-size: 12pt;\"><strong>Priority:</strong> {task_priority}<br /><br /></span><span style=\"font-size: 12pt;\"><span>You can view the task on the following link</span>: <a href=\"{task_link}\">{task_name}</a></span><br /><br /><span style=\"font-size: 12pt;\">Kind Regards,</span><br /><span style=\"font-size: 12pt;\">{email_signature}</span>', '{companyname}', '', 0, 1, 0),
(15, 'tasks', 'task-added-as-follower', 'english', 'Staff Member Added as Follower on Task (Sent to Staff)', 'You are added as follower on task - {task_name}', '<span style=\"font-size: 12pt;\">Hi {staff_firstname}<br /></span><br /><span style=\"font-size: 12pt;\">You have been added as follower on the following task:</span><br /><br /><span style=\"font-size: 12pt;\"><strong>Name:</strong> {task_name}</span><br /><span style=\"font-size: 12pt;\"><strong>Start date:</strong> {task_startdate}</span><br /><br /><span>You can view the task on the following link</span><span>: </span><a href=\"{task_link}\">{task_name}</a><br /><br /><span style=\"font-size: 12pt;\">Kind Regards,</span><br /><span style=\"font-size: 12pt;\">{email_signature}</span>', '{companyname}', '', 0, 1, 0),
(16, 'tasks', 'task-commented', 'english', 'New Comment on Task (Sent to Staff)', 'New Comment on Task - {task_name}', 'Dear {staff_firstname}<br /><br />A comment has been made on the following task:<br /><br /><strong>Name:</strong> {task_name}<br /><strong>Comment:</strong> {task_comment}<br /><br />You can view the task on the following link: <a href=\"{task_link}\">{task_name}</a><br /><br />Kind Regards,<br />{email_signature}', '{companyname}', '', 0, 1, 0),
(17, 'tasks', 'task-added-attachment', 'english', 'New Attachment(s) on Task (Sent to Staff)', 'New Attachment on Task - {task_name}', 'Hi {staff_firstname}<br /><br /><strong>{task_user_take_action}</strong> added an attachment on the following task:<br /><br /><strong>Name:</strong> {task_name}<br /><br />You can view the task on the following link: <a href=\"{task_link}\">{task_name}</a><br /><br />Kind Regards,<br />{email_signature}', '{companyname}', '', 0, 1, 0),
(18, 'estimate', 'estimate-declined-to-staff', 'english', 'Estimate Declined (Sent to Staff)', 'Customer Declined Estimate', '<span style=\"font-size: 12pt;\">Hi</span><br /> <br /><span style=\"font-size: 12pt;\">Customer ({client_company}) declined estimate with number <strong># {estimate_number}</strong></span><br /> <br /><span style=\"font-size: 12pt;\">You can view the estimate on the following link: <a href=\"{estimate_link}\">{estimate_number}</a></span><br /> <br /><span style=\"font-size: 12pt;\">{email_signature}</span>', '{companyname}', '', 0, 1, 0),
(19, 'estimate', 'estimate-accepted-to-staff', 'english', 'Estimate Accepted (Sent to Staff)', 'Customer Accepted Estimate', '<span style=\"font-size: 12pt;\">Hi</span><br /> <br /><span style=\"font-size: 12pt;\">Customer ({client_company}) accepted estimate with number <strong># {estimate_number}</strong></span><br /> <br /><span style=\"font-size: 12pt;\">You can view the estimate on the following link: <a href=\"{estimate_link}\">{estimate_number}</a></span><br /> <br /><span style=\"font-size: 12pt;\">{email_signature}</span>', '{companyname}', '', 0, 1, 0),
(20, 'proposals', 'proposal-client-accepted', 'english', 'Customer Action - Accepted (Sent to Staff)', 'Customer Accepted Proposal', '<div>Hi<br /> <br />Client <strong>{proposal_proposal_to}</strong> accepted the following proposal:<br /> <br /><strong>Number:</strong> {proposal_number}<br /><strong>Subject</strong>: {proposal_subject}<br /><strong>Total</strong>: {proposal_total}<br /> <br />View the proposal on the following link: <a href=\"{proposal_link}\">{proposal_number}</a><br /> <br />Kind Regards,<br />{email_signature}</div>\r\n<div>&nbsp;</div>\r\n<div>&nbsp;</div>\r\n<div>&nbsp;</div>', '{companyname}', '', 0, 1, 0),
(21, 'proposals', 'proposal-send-to-customer', 'english', 'Send Proposal to Customer', '', '', '{companyname}', '', 0, 1, 0),
(22, 'proposals', 'proposal-client-declined', 'english', 'Customer Action - Declined (Sent to Staff)', 'Client Declined Proposal', 'Hi<br /><br />Customer <strong>{proposal_proposal_to}</strong> declined the proposal <strong>{proposal_subject}</strong><br /><br />View the proposal on the following link <a href=\"{proposal_link}\">{proposal_number}</a>&nbsp;or from the admin area.<br /><br />Kind Regards,<br />{email_signature}&nbsp;', '{companyname}', '', 0, 1, 0),
(23, 'proposals', 'proposal-client-thank-you', 'english', 'Thank You Email (Sent to Customer After Accept)', 'Thank for you accepting proposal', '<p>Dear {proposal_proposal_to}</p>\r\n<p><span>Thanks for accepting the proposal.</span><br /><br /><span>I appreciate your acceptance of my proposal. I am excited to work with you and contribute to the success of our project. Let\'s work together to achieve our goals and make a positive impact. Thank you again for your trust in me.<br /></span><br />We look forward to doing business with you.<br /><br />We will contact you as soon as possible<br /><br />Kind Regards,<br />{email_signature}</p>', '{companyname}', '', 0, 1, 0),
(24, 'proposals', 'proposal-comment-to-client', 'english', 'New Comment Â (Sent to Customer/Lead)', 'New Proposal Comment', 'Dear {proposal_proposal_to}<br /> <br />A new comment has been made on the following proposal: <strong>{proposal_number}</strong><br /> <br />You can view and reply to the comment on the following link: <a href=\"{proposal_link}\">{proposal_number}</a><br /> <br />Kind Regards,<br />{email_signature}', '{companyname}', '', 0, 1, 0),
(25, 'proposals', 'proposal-comment-to-admin', 'english', 'New Comment (Sent to Staff) ', 'New Proposal Comment', 'Hi<br /> <br />A new comment has been made to the proposal <strong>{proposal_subject}</strong><br /> <br />You can view and reply to the comment on the following link: <a href=\"{proposal_link}\">{proposal_number}</a>&nbsp;or from the admin area.<br /> <br />{email_signature}', '{companyname}', '', 0, 1, 0),
(26, 'estimate', 'estimate-thank-you-to-customer', 'english', 'Thank You Email (Sent to Customer After Accept)', 'Thank for you accepting estimate', '<span style=\"font-size: 12pt;\">Dear {contact_firstname} {contact_lastname}</span><br /> <br /><span style=\"font-size: 12pt;\">Thank for for accepting the estimate.</span><br /> <br /><span style=\"font-size: 12pt;\">We look forward to doing business with you.</span><br /> <br /><span style=\"font-size: 12pt;\">We will contact you as soon as possible.</span><br /> <br /><span style=\"font-size: 12pt;\">Kind Regards,</span><br /><span style=\"font-size: 12pt;\">{email_signature}</span>', '{companyname}', '', 0, 1, 0),
(27, 'tasks', 'task-deadline-notification', 'english', 'Task Deadline Reminder - Sent to Assigned Members', 'Task Deadline Reminder', 'Hi {staff_firstname}&nbsp;{staff_lastname}<br /><br />This is an automated email from {companyname}.<br /><br />The task <strong>{task_name}</strong> deadline is on <strong>{task_duedate}</strong>. <br />This task is still not finished.<br /><br />You can view the task on the following link: <a href=\"{task_link}\">{task_name}</a><br /><br />Kind Regards,<br />{email_signature}', '{companyname}', '', 0, 1, 0),
(29, 'invoice', 'invoice-payment-recorded-to-staff', 'english', 'Invoice Payment Recorded (Sent to Staff)', 'New Invoice Payment', '<span style=\"font-size: 12pt;\">Hi</span><br /><br /><span style=\"font-size: 12pt;\">Customer recorded payment for invoice <strong># {invoice_number}</strong></span><br /> <br /><span style=\"font-size: 12pt;\">You can view the invoice on the following link: <a href=\"{invoice_link}\">{invoice_number}</a></span><br /> <br /><span style=\"font-size: 12pt;\">Kind Regards,</span><br /><span style=\"font-size: 12pt;\">{email_signature}</span>', '{companyname}', '', 0, 1, 0),
(30, 'ticket', 'auto-close-ticket', 'english', 'Auto Close Ticket', 'Ticket Auto Closed', '<p><span style=\"font-size: 12pt;\">Hi {contact_firstname} {contact_lastname}</span><br /><br /><span style=\"font-size: 12pt;\">Ticket {ticket_subject} has been auto close due to inactivity.</span><br /><br /><span style=\"font-size: 12pt;\"><strong>Ticket #</strong>: <a href=\"{ticket_url}\">{ticket_id}</a></span><br /><span style=\"font-size: 12pt;\"><strong>Department</strong>: {ticket_department}</span><br /><span style=\"font-size: 12pt;\"><strong>Priority:</strong> {ticket_priority}</span><br /><br /><span style=\"font-size: 12pt;\">Kind Regards,</span><br /><span style=\"font-size: 12pt;\">{email_signature}</span></p>', '{companyname}', '', 0, 1, 0),
(31, 'project', 'new-project-discussion-created-to-staff', 'english', 'New Project Discussion (Sent to Project Members)', 'New Project Discussion Created - {project_name}', '<p>Hi {staff_firstname}<br /><br />New project discussion created from <strong>{discussion_creator}</strong><br /><br /><strong>Subject:</strong> {discussion_subject}<br /><strong>Description:</strong> {discussion_description}<br /><br />You can view the discussion on the following link: <a href=\"{discussion_link}\">{discussion_subject}</a><br /><br />Kind Regards,<br />{email_signature}</p>', '{companyname}', '', 0, 1, 0),
(32, 'project', 'new-project-discussion-created-to-customer', 'english', 'New Project Discussion (Sent to Customer Contacts)', 'New Project Discussion Created - {project_name}', '<p>Hello {contact_firstname} {contact_lastname}<br /><br />New project discussion created from <strong>{discussion_creator}</strong><br /><br /><strong>Subject:</strong> {discussion_subject}<br /><strong>Description:</strong> {discussion_description}<br /><br />You can view the discussion on the following link: <a href=\"{discussion_link}\">{discussion_subject}</a><br /><br />Kind Regards,<br />{email_signature}</p>', '{companyname}', '', 0, 1, 0),
(33, 'project', 'new-project-file-uploaded-to-customer', 'english', 'New Project File(s) Uploaded (Sent to Customer Contacts)', 'New Project File(s) Uploaded - {project_name}', '<p>Hello {contact_firstname} {contact_lastname}<br /><br />New project file is uploaded on <strong>{project_name}</strong> from <strong>{file_creator}</strong><br /><br />You can view the project on the following link: <a href=\"{project_link}\">{project_name}</a><br /><br />To view the file in our CRM you can click on the following link: <a href=\"{discussion_link}\">{discussion_subject}</a><br /><br />Kind Regards,<br />{email_signature}</p>', '{companyname}', '', 0, 1, 0),
(34, 'project', 'new-project-file-uploaded-to-staff', 'english', 'New Project File(s) Uploaded (Sent to Project Members)', 'New Project File(s) Uploaded - {project_name}', '<p>Hello&nbsp;{staff_firstname}</p>\r\n<p>New project&nbsp;file is uploaded on&nbsp;<strong>{project_name}</strong> from&nbsp;<strong>{file_creator}</strong></p>\r\n<p>You can view the project on the following link: <a href=\"{project_link}\">{project_name}<br /></a><br />To view&nbsp;the file you can click on the following link: <a href=\"{discussion_link}\">{discussion_subject}</a></p>\r\n<p>Kind Regards,<br />{email_signature}</p>', '{companyname}', '', 0, 1, 0),
(35, 'project', 'new-project-discussion-comment-to-customer', 'english', 'New Discussion Comment  (Sent to Customer Contacts)', 'New Discussion Comment', '<p><span style=\"font-size: 12pt;\">Hello {contact_firstname} {contact_lastname}</span><br /><br /><span style=\"font-size: 12pt;\">New discussion comment has been made on <strong>{discussion_subject}</strong> from <strong>{comment_creator}</strong></span><br /><br /><span style=\"font-size: 12pt;\"><strong>Discussion subject:</strong> {discussion_subject}</span><br /><span style=\"font-size: 12pt;\"><strong>Comment</strong>: {discussion_comment}</span><br /><br /><span style=\"font-size: 12pt;\">You can view the discussion on the following link: <a href=\"{discussion_link}\">{discussion_subject}</a></span><br /><br /><span style=\"font-size: 12pt;\">Kind Regards,</span><br /><span style=\"font-size: 12pt;\">{email_signature}</span></p>', '{companyname}', '', 0, 1, 0),
(36, 'project', 'new-project-discussion-comment-to-staff', 'english', 'New Discussion Comment (Sent to Project Members)', 'New Discussion Comment', '<p>Hi {staff_firstname}<br /><br />New discussion comment has been made on <strong>{discussion_subject}</strong> from <strong>{comment_creator}</strong><br /><br /><strong>Discussion subject:</strong> {discussion_subject}<br /><strong>Comment:</strong> {discussion_comment}<br /><br />You can view the discussion on the following link: <a href=\"{discussion_link}\">{discussion_subject}</a><br /><br />Kind Regards,<br />{email_signature}</p>', '{companyname}', '', 0, 1, 0),
(37, 'project', 'staff-added-as-project-member', 'english', 'Staff Added as Project Member', 'New project assigned to you', '<p>Hi {staff_firstname}<br /><br />New project has been assigned to you.<br /><br />You can view the project on the following link <a href=\"{project_link}\">{project_name}</a><br /><br />{email_signature}</p>', '{companyname}', '', 0, 1, 0),
(38, 'estimate', 'estimate-expiry-reminder', 'english', 'Estimate Expiration Reminder', 'Estimate Expiration Reminder', '<p><span style=\"font-size: 12pt;\">Hello {contact_firstname} {contact_lastname}</span><br /><br /><span style=\"font-size: 12pt;\">The estimate with <strong># {estimate_number}</strong> will expire on <strong>{estimate_expirydate}</strong></span><br /><br /><span style=\"font-size: 12pt;\">You can view the estimate on the following link: <a href=\"{estimate_link}\">{estimate_number}</a></span><br /><br /><span style=\"font-size: 12pt;\">Kind Regards,</span><br /><span style=\"font-size: 12pt;\">{email_signature}</span></p>', '{companyname}', '', 0, 1, 0),
(39, 'proposals', 'proposal-expiry-reminder', 'english', 'Proposal Expiration Reminder', 'Proposal Expiration Reminder', '<p>Hello {proposal_proposal_to}<br /><br /></p>\n<p><span>I hope this message finds you well. I wanted to remind you that the proposal {proposal_number} we sent to you for the {proposal_products} is set to expire on <strong>{proposal_open_till}</strong>.<br /><br />You can view the proposal on the following link: <a href=\"{proposal_link}\">{proposal_number}</a><br /></span></p>\n<p><span>If you have any further questions or require any modifications before the deadline, please feel free to reach out. We are here to assist you and ensure that all your needs are met.</span></p>\n<p><span>Thank you for us. for your project. We look forward to your response.</span></p>\n<p>Kind Regards,<br />{email_signature}</p>', '{companyname}', '', 0, 1, 0),
(40, 'staff', 'new-staff-created', 'english', 'New Staff Created (Welcome Email)', 'You are added as staff member', 'Hi {staff_firstname}<br /><br />You are added as member on our CRM.<br /><br />Please use the following logic credentials:<br /><br /><strong>Email:</strong> {staff_email}<br /><strong>Password:</strong> {password}<br /><br />Click <a href=\"{admin_url}\">here </a>to login in the dashboard.<br /><br />Best Regards,<br />{email_signature}', '{companyname}', '', 0, 1, 0),
(41, 'client', 'contact-forgot-password', 'english', 'Forgot Password', 'Create New Password', '<h2>Create a new password</h2>\r\nForgot your password?<br /> To create a new password, just follow this link:<br /> <br /><a href=\"{reset_password_url}\">Reset Password</a><br /> <br /> You received this email, because it was requested by a {companyname}&nbsp;user. This is part of the procedure to create a new password on the system. If you DID NOT request a new password then please ignore this email and your password will remain the same. <br /><br /> {email_signature}', '{companyname}', '', 0, 1, 0),
(42, 'client', 'contact-password-reseted', 'english', 'Password Reset - Confirmation', 'Your password has been changed', '<strong><span style=\"font-size: 14pt;\">You have changed your password.</span><br /></strong><br /> Please, keep it in your records so you don\'t forget it.<br /> <br /> Your email address for login is: {contact_email}<br /><br />If this wasnt you, please contact us.<br /><br />{email_signature}', '{companyname}', '', 0, 1, 0),
(43, 'client', 'contact-set-password', 'english', 'Set New Password', 'Set new password on {companyname} ', '<h2><span style=\"font-size: 14pt;\">Setup your new password on {companyname}</span></h2>\r\nPlease use the following link to set up your new password:<br /><br /><a href=\"{set_password_url}\">Set new password</a><br /><br />Keep it in your records so you don\'t forget it.<br /><br />Please set your new password in <strong>48 hours</strong>. After that, you won\'t be able to set your password because this link will expire.<br /><br />You can login at: <a href=\"{crm_url}\">{crm_url}</a><br />Your email address for login: {contact_email}<br /><br />{email_signature}', '{companyname}', '', 0, 1, 0),
(44, 'staff', 'staff-forgot-password', 'english', 'Forgot Password', 'Create New Password', '<h2><span style=\"font-size: 14pt;\">Create a new password</span></h2>\r\nForgot your password?<br /> To create a new password, just follow this link:<br /> <br /><a href=\"{reset_password_url}\">Reset Password</a><br /> <br /> You received this email, because it was requested by a <strong>{companyname}</strong>&nbsp;user. This is part of the procedure to create a new password on the system. If you DID NOT request a new password then please ignore this email and your password will remain the same. <br /><br /> {email_signature}', '{companyname}', '', 0, 1, 0),
(45, 'staff', 'staff-password-reseted', 'english', 'Password Reset - Confirmation', 'Your password has been changed', '<span style=\"font-size: 14pt;\"><strong>You have changed your password.<br /></strong></span><br /> Please, keep it in your records so you don\'t forget it.<br /> <br /> Your email address for login is: {staff_email}<br /><br /> If this wasnt you, please contact us.<br /><br />{email_signature}', '{companyname}', '', 0, 1, 0),
(46, 'project', 'assigned-to-project', 'english', 'New Project Created (Sent to Customer Contacts)', 'New Project Created', '<p>Hello&nbsp;{contact_firstname}&nbsp;{contact_lastname}</p>\r\n<p>New project is assigned to your company.<br /><br /><strong>Project Name:</strong>&nbsp;{project_name}<br /><strong>Project Start Date:</strong>&nbsp;{project_start_date}</p>\r\n<p>You can view the project on the following link:&nbsp;<a href=\"{project_link}\">{project_name}</a></p>\r\n<p>We are looking forward hearing from you.<br /><br />Kind Regards,<br />{email_signature}</p>', '{companyname}', '', 0, 1, 0),
(47, 'tasks', 'task-added-attachment-to-contacts', 'english', 'New Attachment(s) on Task (Sent to Customer Contacts)', 'New Attachment on Task - {task_name}', '<span>Hi {contact_firstname} {contact_lastname}</span><br /><br /><strong>{task_user_take_action}</strong><span> added an attachment on the following task:</span><br /><br /><strong>Name:</strong><span> {task_name}</span><br /><br /><span>You can view the task on the following link: </span><a href=\"{task_link}\">{task_name}</a><br /><br /><span>Kind Regards,</span><br /><span>{email_signature}</span>', '{companyname}', '', 0, 1, 0),
(48, 'tasks', 'task-commented-to-contacts', 'english', 'New Comment on Task (Sent to Customer Contacts)', 'New Comment on Task - {task_name}', '<span>Dear {contact_firstname} {contact_lastname}</span><br /><br /><span>A comment has been made on the following task:</span><br /><br /><strong>Name:</strong><span> {task_name}</span><br /><strong>Comment:</strong><span> {task_comment}</span><br /><br /><span>You can view the task on the following link: </span><a href=\"{task_link}\">{task_name}</a><br /><br /><span>Kind Regards,</span><br /><span>{email_signature}</span>', '{companyname}', '', 0, 1, 0),
(49, 'leads', 'new-lead-assigned', 'english', 'New Lead Assigned to Staff Member', 'New lead assigned to you', '<p style=\"text-align: justify;\">Hello {lead_assigned}<br /><br />A new lead is assigned to you.<br /><br /><strong>Lead Name:</strong>&nbsp;{lead_name}<br /><strong>Lead COntact No:</strong> {lead_phonenumber}<br /><strong>Lead Email:</strong>&nbsp;{lead_email}<br />Description: {lead_description}<br /><br />You can view the lead on the following link: <a href=\"{lead_link}\">{lead_name}</a><br /><br />Kind Regards,<br />{email_signature}</p>', '{companyname}', '', 0, 0, 0),
(50, 'client', 'client-statement', 'english', 'Statement - Account Summary', 'Account Statement from {statement_from} to {statement_to}', 'Dear {contact_firstname} {contact_lastname}, <br /><br />Its been a great experience working with you.<br /><br />Attached with this email is a list of all transactions for the period between {statement_from} to {statement_to}<br /><br />For your information your account balance due is total:&nbsp;{statement_balance_due}<br /><br />Please contact us if you need more information.<br /> <br />Kind Regards,<br />{email_signature}', '{companyname}', '', 0, 1, 0),
(51, 'ticket', 'ticket-assigned-to-admin', 'english', 'New Ticket Assigned (Sent to Staff)', 'New support ticket has been assigned to you', '<p><span style=\"font-size: 12pt;\">Hi</span></p>\r\n<p><span style=\"font-size: 12pt;\">A new support ticket&nbsp;has been assigned to you.</span><br /><br /><span style=\"font-size: 12pt;\"><strong>Subject</strong>: {ticket_subject}</span><br /><span style=\"font-size: 12pt;\"><strong>Department</strong>: {ticket_department}</span><br /><span style=\"font-size: 12pt;\"><strong>Priority</strong>: {ticket_priority}</span><br /><br /><span style=\"font-size: 12pt;\"><strong>Ticket message:</strong></span><br /><span style=\"font-size: 12pt;\">{ticket_message}</span><br /><br /><span style=\"font-size: 12pt;\">You can view the ticket on the following link: <a href=\"{ticket_url}\">#{ticket_id}</a></span><br /><br /><span style=\"font-size: 12pt;\">Kind Regards,</span><br /><span style=\"font-size: 12pt;\">{email_signature}</span></p>', '{companyname}', '', 0, 1, 0),
(52, 'client', 'new-client-registered-to-admin', 'english', 'New Customer Registration (Sent to admins)', 'New Customer Registration', 'Hello.<br /><br />New customer registration on your customer portal:<br /><br /><strong>Firstname:</strong>&nbsp;{contact_firstname}<br /><strong>Lastname:</strong>&nbsp;{contact_lastname}<br /><strong>Company:</strong>&nbsp;{client_company}<br /><strong>Email:</strong>&nbsp;{contact_email}<br /><br />Best Regards', '{companyname}', '', 0, 1, 0),
(53, 'leads', 'new-web-to-lead-form-submitted', 'english', 'Web to lead form submitted - Sent to lead', '', '', '{companyname}', '', 0, 1, 0),
(54, 'staff', 'two-factor-authentication', 'english', 'Two Factor Authentication', 'Confirm Your Login', '<p>Hi {staff_firstname}</p>\r\n<p style=\"text-align: left;\">You received this email because you have enabled two factor authentication in your account.<br />Use the following code to confirm your login:</p>\r\n<p style=\"text-align: left;\"><span style=\"font-size: 18pt;\"><strong>{two_factor_auth_code}<br /><br /></strong><span style=\"font-size: 12pt;\">{email_signature}</span><strong><br /><br /><br /><br /></strong></span></p>', '{companyname}', '', 0, 1, 0),
(55, 'project', 'project-finished-to-customer', 'english', 'Project Marked as Finished (Sent to Customer Contacts)', 'Project Marked as Finished', '<p>Hello&nbsp;{contact_firstname}&nbsp;{contact_lastname}</p>\r\n<p>You are receiving this email because project&nbsp;<strong>{project_name}</strong> has been marked as finished. This project is assigned under your company and we just wanted to keep you up to date.<br /><br />You can view the project on the following link:&nbsp;<a href=\"{project_link}\">{project_name}</a></p>\r\n<p>If you have any questions don\'t hesitate to contact us.<br /><br />Kind Regards,<br />{email_signature}</p>', '{companyname}', '', 0, 1, 0),
(56, 'credit_note', 'credit-note-send-to-client', 'english', 'Send Credit Note To Email', 'Credit Note With Number #{credit_note_number} Created', 'Dear&nbsp;{contact_firstname}&nbsp;{contact_lastname}<br /><br />We have attached the credit note with number <strong>#{credit_note_number} </strong>for your reference.<br /><br /><strong>Date:</strong>&nbsp;{credit_note_date}<br /><strong>Total Amount:</strong>&nbsp;{credit_note_total}<br /><br /><span style=\"font-size: 12pt;\">Please contact us for more information.</span><br /> <br /><span style=\"font-size: 12pt;\">Kind Regards,</span><br /><span style=\"font-size: 12pt;\">{email_signature}</span>', '{companyname}', '', 0, 1, 0),
(57, 'tasks', 'task-status-change-to-staff', 'english', 'Task Status Changed (Sent to Staff)', 'Task Status Changed', '<span style=\"font-size: 12pt;\">Hi {staff_firstname}</span><br /><br /><span style=\"font-size: 12pt;\"><strong>{task_user_take_action}</strong> marked task as <strong>{task_status}</strong></span><br /><br /><span style=\"font-size: 12pt;\"><strong>Name:</strong> {task_name}</span><br /><span style=\"font-size: 12pt;\"><strong>Due date:</strong> {task_duedate}</span><br /><br /><span style=\"font-size: 12pt;\">You can view the task on the following link: <a href=\"{task_link}\">{task_name}</a></span><br /><br /><span style=\"font-size: 12pt;\">Kind Regards,</span><br /><span style=\"font-size: 12pt;\">{email_signature}</span>', '{companyname}', '', 0, 1, 0),
(58, 'tasks', 'task-status-change-to-contacts', 'english', 'Task Status Changed (Sent to Customer Contacts)', 'Task Status Changed', '<span style=\"font-size: 12pt;\">Hi {contact_firstname} {contact_lastname}</span><br /><br /><span style=\"font-size: 12pt;\"><strong>{task_user_take_action}</strong> marked task as <strong>{task_status}</strong></span><br /><br /><span style=\"font-size: 12pt;\"><strong>Name:</strong> {task_name}</span><br /><span style=\"font-size: 12pt;\"><strong>Due date:</strong> {task_duedate}</span><br /><br /><span style=\"font-size: 12pt;\">You can view the task on the following link: <a href=\"{task_link}\">{task_name}</a></span><br /><br /><span style=\"font-size: 12pt;\">Kind Regards,</span><br /><span style=\"font-size: 12pt;\">{email_signature}</span>', '{companyname}', '', 0, 1, 0),
(59, 'staff', 'reminder-email-staff', 'english', 'Staff Reminder Email', 'You Have a New Reminder!', '<p>Hello&nbsp;{staff_firstname}<br /><br /><strong>You have a new reminder&nbsp;linked to&nbsp;{staff_reminder_relation_name}!<br /><br />Reminder description:</strong><br />{staff_reminder_description}<br /><br />Click <a href=\"{staff_reminder_relation_link}\">here</a> to view&nbsp;<a href=\"{staff_reminder_relation_link}\">{staff_reminder_relation_name}</a><br /><br />Best Regards<br /><br /></p>', '{companyname}', '', 0, 1, 0),
(60, 'contract', 'contract-comment-to-client', 'english', 'New Comment Â (Sent to Customer Contacts)', 'New Agreement Comment', 'Dear {contact_firstname} {contact_lastname}<br /> <br />A new comment has been made on the following agreement: <strong>{agreement_subject}</strong><br /> <br />You can view and reply to the comment on the following link: <a href=\"{agreement_link}\">{agreement_subject}</a><br /> <br />Kind Regards,<br />{email_signature}', '{companyname}', '', 0, 1, 0),
(61, 'contract', 'contract-comment-to-admin', 'english', 'New Comment (Sent to Staff) ', 'New Agreement Comment', 'Hi {staff_firstname}<br /><br />A new comment has been made to the agreement&nbsp;<strong>{agreement_subject}</strong><br /><br />You can view and reply to the comment on the following link: <a href=\"{agreement_link}\">{agreement_subject}</a>&nbsp;or from the admin area.<br /><br />{email_signature}', '{companyname}', '', 0, 1, 0),
(62, 'subscriptions', 'send-subscription', 'english', 'Send Subscription to Customer', 'Subscription Created', 'Hello&nbsp;{contact_firstname}&nbsp;{contact_lastname}<br /><br />We have prepared the subscription&nbsp;<strong>{subscription_name}</strong> for your company.<br /><br />Click <a href=\"{subscription_link}\">here</a> to review the subscription and subscribe.<br /><br />Best Regards,<br />{email_signature}', '{companyname}', '', 0, 1, 0),
(63, 'subscriptions', 'subscription-payment-failed', 'english', 'Subscription Payment Failed', 'Your most recent invoice payment failed', 'Hello&nbsp;{contact_firstname}&nbsp;{contact_lastname}<br /><br br=\"\" />Unfortunately, your most recent invoice payment for&nbsp;<strong>{subscription_name}</strong> was declined.<br /><br /> This could be due to a change in your card number, your card expiring,<br /> cancellation of your credit card, or the card issuer not recognizing the<br /> payment and therefore taking action to prevent it.<br /><br /> Please update your payment information as soon as possible by logging in here:<br /><a href=\"{crm_url}\">{crm_url}</a><br /><br />Best Regards,<br />{email_signature}', '{companyname}', '', 0, 1, 0),
(64, 'subscriptions', 'subscription-canceled', 'english', 'Subscription Canceled (Sent to customer primary contact)', 'Your subscription has been canceled', 'Hello&nbsp;{contact_firstname}&nbsp;{contact_lastname}<br /><br />Your subscription&nbsp;<strong>{subscription_name} </strong>has been canceled, if you have any questions don\'t hesitate to contact us.<br /><br />It was a pleasure doing business with you.<br /><br />Best Regards,<br />{email_signature}', '{companyname}', '', 0, 1, 0),
(65, 'subscriptions', 'subscription-payment-succeeded', 'english', 'Subscription Payment Succeeded (Sent to customer primary contact)', 'Subscription  Payment Receipt - {subscription_name}', 'Hello&nbsp;{contact_firstname}&nbsp;{contact_lastname}<br /><br />This email is to let you know that we received your payment for subscription&nbsp;<strong>{subscription_name}&nbsp;</strong>of&nbsp;<strong><span>{payment_total}<br /><br /></span></strong>The invoice associated with it is now with status&nbsp;<strong>{invoice_status}<br /></strong><br />Thank you for your confidence.<br /><br />Best Regards,<br />{email_signature}', '{companyname}', '', 0, 1, 0),
(66, 'contract', 'contract-expiration-to-staff', 'english', 'Agreement Expiration Reminder (Sent to Staff)', 'Agreement Expiration Reminder', 'Hi {staff_firstname}<br /><br /><span style=\"font-size: 12pt;\">This is a reminder that the following agreement will expire soon:</span><br /><br /><span style=\"font-size: 12pt;\"><strong>Subject:</strong> {agreement_subject}</span><br /><span style=\"font-size: 12pt;\"><strong>Description:</strong> {agreement_description}</span><br /><span style=\"font-size: 12pt;\"><strong>Date Start:</strong> {agreement_datestart}</span><br /><span style=\"font-size: 12pt;\"><strong>Date End:</strong> {agreement_dateend}</span><br /><br /><span style=\"font-size: 12pt;\">Kind Regards,</span><br /><span style=\"font-size: 12pt;\">{email_signature}</span>', '{companyname}', '', 0, 1, 0),
(67, 'gdpr', 'gdpr-removal-request', 'english', 'Removal Request From Contact (Sent to administrators)', 'Data Removal Request Received', 'Hello&nbsp;{staff_firstname}&nbsp;{staff_lastname}<br /><br />Data removal has been requested by&nbsp;{contact_firstname} {contact_lastname}<br /><br />You can review this request and take proper actions directly from the admin area.', '{companyname}', '', 0, 1, 0),
(68, 'gdpr', 'gdpr-removal-request-lead', 'english', 'Removal Request From Lead (Sent to administrators)', 'Data Removal Request Received', 'Hello&nbsp;{staff_firstname}&nbsp;{staff_lastname}<br /><br />Data removal has been requested by {lead_name}<br /><br />You can review this request and take proper actions directly from the admin area.<br /><br />To view the lead inside the admin area click here:&nbsp;<a href=\"{lead_link}\">{lead_link}</a>', '{companyname}', '', 0, 1, 0),
(69, 'client', 'client-registration-confirmed', 'english', 'Customer Registration Confirmed', 'Your registration is confirmed', '<p>Dear {contact_firstname} {contact_lastname}<br /><br />We just wanted to let you know that your registration at&nbsp;{companyname} is successfully confirmed and your account is now active.<br /><br />You can login at&nbsp;<a href=\"{crm_url}\">{crm_url}</a> with the email and password you provided during registration.<br /><br />Please contact us if you need any help.<br /><br />Kind Regards, <br />{email_signature}</p>\r\n<p><br />(This is an automated email, so please don\'t reply to this email address)</p>', '{companyname}', '', 0, 1, 0),
(70, 'contract', 'contract-signed-to-staff', 'english', 'Agreement Signed (Sent to Staff)', 'Customer Signed a Agreement', 'Hi {staff_firstname}<br /><br />A agreement with subject&nbsp;<strong>{agreement_subject} </strong>has been successfully signed by the customer.<br /><br />You can view the agreement at the following link: <a href=\"{agreement_link}\">{agreement_subject}</a>&nbsp;or from the admin area.<br /><br />{email_signature}', '{companyname}', '', 0, 1, 0),
(71, 'subscriptions', 'customer-subscribed-to-staff', 'english', 'Customer Subscribed to a Subscription (Sent to administrators and subscription creator)', 'Customer Subscribed to a Subscription', 'The customer <strong>{client_company}</strong> subscribed to a subscription with name&nbsp;<strong>{subscription_name}</strong><br /><br /><strong>ID</strong>:&nbsp;{subscription_id}<br /><strong>Subscription name</strong>:&nbsp;{subscription_name}<br /><strong>Subscription description</strong>:&nbsp;{subscription_description}<br /><br />You can view the subscription by clicking <a href=\"{subscription_link}\">here</a><br />\r\n<div style=\"text-align: center;\"><span style=\"font-size: 10pt;\">&nbsp;</span></div>\r\nBest Regards,<br />{email_signature}<br /><br /><span style=\"font-size: 10pt;\"><span style=\"color: #999999;\">You are receiving this email because you are either administrator or you are creator of the subscription.</span></span>', '{companyname}', '', 0, 1, 0),
(72, 'client', 'contact-verification-email', 'english', 'Email Verification (Sent to Contact After Registration)', 'Verify Email Address', '<p>Hello&nbsp;{contact_firstname}<br /><br />Please click the button below to verify your email address.<br /><br /><a href=\"{email_verification_url}\">Verify Email Address</a><br /><br />If you did not create an account, no further action is required</p>\r\n<p><br />{email_signature}</p>', '{companyname}', '', 0, 1, 0),
(73, 'client', 'new-customer-profile-file-uploaded-to-staff', 'english', 'New Customer Profile File(s) Uploaded (Sent to Staff)', 'Customer Uploaded New File(s) in Profile', 'Hi!<br /><br />New file(s) is uploaded into the customer ({client_company}) profile by&nbsp;{contact_firstname}<br /><br />You can check the uploaded files into the admin area by clicking <a href=\"{customer_profile_files_admin_link}\">here</a> or at the following link:&nbsp;{customer_profile_files_admin_link}<br /><br />{email_signature}', '{companyname}', '', 0, 1, 0),
(74, 'staff', 'event-notification-to-staff', 'english', 'Event Notification (Calendar)', 'Upcoming Event - {event_title}', 'Hi {staff_firstname}! <br /><br />This is a reminder for event <a href=\\\"{event_link}\\\">{event_title}</a> scheduled at {event_start_date}. <br /><br />Regards.', '{companyname}', '', 0, 1, 0),
(75, 'approve', 'send-request-approve', 'english', 'Send Approval Request', 'Require Approval', '<p>Hi {staff_firstname}<br /><br />You have received a request to approve the {object_type}.<br /><br />You can view the {object_type} on the following link <a href=\"{object_link}\">{object_name}</a><br /><br />{email_signature}</p>', '{companyname}', NULL, 0, 1, 0),
(76, 'approve', 'send-request-approve', 'vietnamese', 'Gửi yêu cầu phê duyệt', 'Yêu cầu phê duyệt', 'Xin ch&agrave;o {staff_firstname} {staff_lastname}<br /><br />Bạn đã nhận được yêu cầu phê duyệt {object_type} mới.<br /><br />Bạn c&oacute; thể xem hóa đơn tại đ&acirc;y&nbsp;<a href=\"{object_link}\">{object_name}</a><br /><br />{email_signature}', '{companyname}', NULL, 0, 1, 0),
(77, 'approve', 'send_rejected', 'english', 'Send Rejected', 'The {object_type} has been rejected', '<p>Hi {staff_firstname}<br /><br />Your {object_type} has been rejected.<br /><br />You can view the {object_type} on the following link <a href=\"{object_link}\">{object_name}</a><br /><br />{email_signature}</p>', '{companyname}', NULL, 0, 1, 0),
(78, 'approve', 'send_rejected', 'vietnamese', 'Gửi từ chối', '{object_type} đã bị từ chối', 'Xin ch&agrave;o {staff_firstname} {staff_lastname}<br /><br />{object_type} của bạn đã bị từ chối.<br /><br />Bạn c&oacute; thể xem {object_type} tại đ&acirc;y&nbsp;<a href=\"{object_link}\">{object_name}</a><br /><br />{email_signature}', '{companyname}', NULL, 0, 1, 0),
(79, 'approve', 'send_approve', 'english', 'Send Approve', 'The {object_type} has been approved', '<p>Hi {staff_firstname}<br /><br />Your {object_type} has been approved.<br /><br />You can view the {object_type} on the following link <a href=\"{object_link}\">{object_name}</a><br /><br />{email_signature}</p>', '{companyname}', NULL, 0, 1, 0),
(80, 'approve', 'send_approve', 'vietnamese', 'Gửi phê duyệt', '{object_type} đã được phê duyệt', 'Xin ch&agrave;o {staff_firstname} {staff_lastname}<br /><br />{object_type} của bạn đã được phê duyệt.<br /><br />Bạn c&oacute; thể xem {object_type} tại đ&acirc;y&nbsp;<a href=\"{object_link}\">{object_name}</a><br /><br />{email_signature}', '{companyname}', NULL, 0, 1, 0);
INSERT INTO `tblemailtemplates` (`emailtemplateid`, `type`, `slug`, `language`, `name`, `subject`, `message`, `fromname`, `fromemail`, `plaintext`, `active`, `order`) VALUES
(81, 'proposalterms', 'proposalsterms_1', 'english', 'Term 1', 'Default Template', '<p></p>\r\n<table border=\"1\" style=\"height: 56px; width: 100%; border-style: solid 1px; border-color: #000000; border-collapse: collapse;\">\r\n<tbody>\r\n<tr style=\"height: 28px;\">\r\n<td style=\"width: 25%; height: 28px;\"><strong>Place Of Loading</strong></td>\r\n<td style=\"width: 25%; height: 28px;\"><strong>Place Of Discharge</strong></td>\r\n<td style=\"width: 25%; height: 28px;\"><strong>Payment Term</strong></td>\r\n<td style=\"width: 25%; height: 28px;\"><strong>Shipment Term</strong></td>\r\n</tr>\r\n<tr style=\"height: 28px;\">\r\n<td style=\"width: 25%; height: 28px;\">{loading_place}</td>\r\n<td style=\"width: 25%; height: 28px;\">{discharge_place}</td>\r\n<td style=\"width: 25%; height: 28px;\">{payment_term}</td>\r\n<td style=\"width: 25%; height: 28px;\">{shipment_term}</td>\r\n</tr>\r\n</tbody>\r\n</table>\r\n<p>{proposal_items}<br /><br /></p>\r\n<table border=\"1\" style=\"height: 50px; width: 100%; border-color: #000000; border-collapse: collapse;\">\r\n<tbody>\r\n<tr style=\"height: 39px;\">\r\n<td style=\"width: 50%; height: 39px;\"><strong>Bank Details :</strong><strong><br /></strong></td>\r\n<td style=\"width: 50%; height: 39px;\"><strong>Company Details :<br /></strong></td>\r\n</tr>\r\n<tr style=\"height: 17px;\">\r\n<td style=\"width: 50%; height: 17px;\">{bank_details}<strong><br /></strong></td>\r\n<td style=\"width: 50%; height: 17px;\"><strong>&nbsp;</strong>GST Number : {company_gst_number}<br />&nbsp;PAN/ICE Number : {company_pan_number}<br />&nbsp;TAN Number : {company_tan_number}</td>\r\n</tr>\r\n</tbody>\r\n</table>\r\n<br />\r\n<table border=\"1\" style=\"height: 34px; width: 100%; border-color: #000000; border-collapse: collapse;\">\r\n<tbody>\r\n<tr style=\"height: 17px;\">\r\n<td style=\"width: 50%; height: 17px;\"><strong>Delivery Terms:</strong></td>\r\n<td style=\"width: 50%; height: 17px;\"><strong>Notes :&nbsp;</strong></td>\r\n</tr>\r\n<tr style=\"height: 17px;\">\r\n<td style=\"width: 50%; height: 17px;\">{delivery_term}</td>\r\n<td style=\"width: 50%; height: 17px;\">{proposal_notes}</td>\r\n</tr>\r\n</tbody>\r\n</table>\r\n<br />\r\n<table border=\"1\" style=\"height: 102px; width: 100%; border-color: #000000; border-collapse: collapse;\">\r\n<tbody>\r\n<tr style=\"height: 102px;\">\r\n<td style=\"width: 50%; height: 102px;\"><strong>The Seller :</strong><br /><strong>For and On Behalf of:</strong><br /><br /><br /><br /><br /><br /><strong>Name Of Signing Authority:</strong><br /><strong>Designation:</strong></td>\r\n<td style=\"width: 50%; height: 102px;\"><strong>The Seller :</strong><br /><strong>For and On Behalf of:<br /></strong><br /><br />{signature_section}<br /><br /><br /><strong>Name Of Signing Authority:</strong><br /><strong>Designation:</strong></td>\r\n</tr>\r\n</tbody>\r\n</table>', '', '', 0, 1, 1),
(82, 'proposalterms', 'proposalsterms_2', 'english', 'Term 2', '', '', '{companyname}', '', 0, 1, 15),
(83, 'proposalterms', 'proposalsterms_3', 'english', 'Term 3', '', '', '{companyname}', '', 0, 1, 20),
(84, 'proposalterms', 'proposalsterms_4', 'english', 'Term 4', '', '', '{companyname}', '', 0, 1, 5),
(85, 'proposalterms', 'proposalsterms_5', 'english', 'Term 5', '', '', '{companyname}', '', 0, 1, 3),
(86, 'proposalterms', 'proposalsterms_6', 'english', 'Term 6', '', '', '{companyname}', '', 0, 1, 2),
(87, 'proposalterms', 'proposalsterms_7', 'english', 'Term 7', '', '', '{companyname}', '', 0, 1, 17),
(88, 'proposalterms', 'proposalsterms_8', 'english', 'Term 8', '', '', '{companyname}', '', 0, 1, 12),
(89, 'proposalterms', 'proposalsterms_9', 'english', 'Term 9', '', '', '{companyname}', '', 0, 1, 8),
(90, 'proposalterms', 'proposalsterms_10', 'english', 'Term 10', '', '', '{companyname}', '', 0, 1, 7),
(91, 'proposalterms', 'proposalsterms_11', 'english', 'Term 11', '', '', '{companyname}', '', 0, 1, 10),
(92, 'proposalterms', 'proposalsterms_12', 'english', 'Term 12', '', '', '{companyname}', '', 0, 1, 16),
(93, 'proposalterms', 'proposalsterms_13', 'english', 'Term 13', '', '', '{companyname}', '', 0, 1, 13),
(94, 'proposalterms', 'proposalsterms_14', 'english', 'Term 14', '', '', '{companyname}', '', 0, 1, 18),
(95, 'proposalterms', 'proposalsterms_15', 'english', 'Term 15', '', '', '{companyname}', '', 0, 1, 11),
(96, 'proposalterms', 'proposalsterms_16', 'english', 'Term 16', '', '', '{companyname}', '', 0, 1, 9),
(97, 'proposalterms', 'proposalsterms_17', 'english', 'Term 17', '', '', '{companyname}', '', 0, 1, 14),
(98, 'proposalterms', 'proposalsterms_18', 'english', 'Term 18', '', '', '{companyname}', '', 0, 1, 4),
(99, 'proposalterms', 'proposalsterms_19', 'english', 'Term 19', '', '', '{companyname}', '', 0, 1, 6),
(100, 'proposalterms', 'proposalsterms_20', 'english', 'Term 20', '', '', '{companyname}', '', 0, 1, 19),
(101, 'proposalterms', 'proposalsterms_21', 'english', 'Term 21', '', '', '{companyname}', '', 0, 1, 21),
(102, 'proposalterms', 'proposalsterms_22', 'english', 'Term 22', '', '', '{companyname}', '', 0, 1, 22),
(103, 'proposalterms', 'proposalsterms_23', 'english', 'Term 23', '', '', '{companyname}', '', 0, 1, 24),
(104, 'proposalterms', 'proposalsterms_24', 'english', 'Term 24', '', '', '{companyname}', '', 0, 1, 23),
(105, 'proposalterms', 'proposalsterms_25', 'english', 'Term 25', '', '', '{companyname}', '', 0, 1, 25),
(106, 'leads', 'lead-customer-inquiry-form-send', 'english', 'Lead customer inquiry form send', 'Inquiry Form', '<div>\r\n<div><span>Dear </span><span>{lead_name}</span><span>,</span></div>\r\n<div><span><br />I hope you\'re doing well. {product_description}</span><span><br /></span><span><br />Kindly complete it at your earliest convenience using the link below:<br /><br /></span><span>{inquiry_form_link}</span></div>\r\n<div><span>&nbsp; &nbsp; &nbsp; &nbsp; <br /></span><span>Please take a few minutes to fill out the form at your earliest convenience. Please feel free to reach out if you have any questions or require further assistance.<br /><br />Thank you for your prompt attention to this matter.</span></div>\r\n<div><span>&nbsp; &nbsp; &nbsp; &nbsp; </span></div>\r\n<div><span>{email_signature}</span></div>\r\n<div></div>\r\n</div>', '{companyname}', '', 0, 1, 0),
(107, 'leads', 'lead-customer-inquiry-form-not-approved', 'english', 'Lead customer inquiry form not approved', 'Inquiry Form Not Approved', '<div>\r\n<div><span>Dear </span><span>{lead_name}</span><span>,</span></div>\r\n<br />\r\n<div><span>&nbsp; &nbsp; &nbsp; &nbsp; Your form not approved due to {inquiry_form_not_approved_reason}. kindly please update the question answer on form using below link.</span></div>\r\n<div><span>&nbsp; &nbsp; &nbsp; &nbsp; </span></div>\r\n<div><span>Form Link : {inquiry_form_link}</span></div>\r\n<div><span>&nbsp; &nbsp; &nbsp; &nbsp; </span></div>\r\n<div><span>{email_signature}</span></div>\r\n</div>', '{companyname}', '', 0, 1, 0),
(108, 'leads', 'lead-customer-inquiry-form-approved', 'english', 'Lead customer inquiry form approved', 'Inquiry Form Approved', '<div><span>Dear </span><span>{lead_name}</span><span>,</span></div>\r\n<br />\r\n<div><span>&nbsp; &nbsp; &nbsp; &nbsp; Your form has been approved</span><span style=\"font-size: 12pt;\">.</span></div>\r\n<div><span>&nbsp; &nbsp; &nbsp; &nbsp; </span></div>\r\n<div><span>{email_signature}<br /></span></div>', '{companyname}', '', 0, 1, 0),
(109, 'vendors', 'vendor-quotation-form-approved', 'english', 'Vendor quotation form approved', 'Quotation Approved', '<div><span>Dear {vendor_name}</span><span>,</span></div>\r\n<br />\r\n<div><span>&nbsp; &nbsp; &nbsp; &nbsp; Your quotation form has been approved</span><span style=\"font-size: 12pt;\">.</span></div>\r\n<div><span>&nbsp; &nbsp; &nbsp; &nbsp; </span></div>\r\n<div><span>{email_signature}<br /></span></div>', '{companyname}', '', 0, 1, 0),
(110, 'vendors', 'vendor-quotation-form-not-approved', 'english', 'Vendor quotation form not approved', 'Quotation Not Approved', '<div>\r\n<div><span>Dear {vendor_name}</span><span>,</span></div>\r\n<br />\r\n<div><span>&nbsp; &nbsp; &nbsp; &nbsp; Your quotation form not approved due to {reject_note}. kindly please update the question answer on form using below link.</span></div>\r\n<div><span>&nbsp; &nbsp; &nbsp; &nbsp; </span></div>\r\n<div><span>Form Link : {quotation_form_link}</span></div>\r\n<div><span>&nbsp; &nbsp; &nbsp; &nbsp; </span></div>\r\n<div><span>{email_signature}</span></div>\r\n</div>', '{companyname}', '', 0, 1, 0),
(111, 'vendors', 'vendor-quotation-form-send', 'english', 'Vendor Quotation Form Send', 'Quotation Form', '<div>\r\n<div><span>Dear </span><span>{vendor_name}</span><span>,</span></div>\r\n<br />\r\n<div><span>&nbsp; &nbsp; &nbsp; &nbsp; I hope this message finds you well. Please fill the quotation form</span><span>. You can access the form through the following link: {quotation_form_link}</span></div>\r\n<div><span>&nbsp; &nbsp; &nbsp; &nbsp; </span></div>\r\n<div><span>&nbsp; &nbsp; &nbsp; &nbsp; Please let me know if there\'s anything else you need from me. I appreciate your assistance.</span></div>\r\n<div><span>&nbsp; &nbsp; &nbsp; &nbsp; </span></div>\r\n<div><span>{email_signature}</span></div>\r\n</div>', '{companyname}', '', 0, 1, 0),
(112, 'staff', 'reminder-customer-meeting-email-send', 'english', 'Reminder customer meeting email send', 'You Have a New Meeting Reminder!', '<p>Hello {customer_name},</p>\r\n<p>We have scheduled a meeting regarding <strong>{product_name}</strong> at <strong>{meeting_time}</strong> on <strong>{meeting_platform}&nbsp;</strong><br />Here is the meeting link: {meeting_link}.</p>\r\n<p>{email_signature}</p>', '{companyname}', '', 0, 1, 0),
(113, 'contract', 'contract-signed-otp-send', 'english', 'Agreement Sign OTP Verification', 'OTP for Agreement Sign', 'Hi<br /><br />Your one time password (OTP)&nbsp; <strong>{otp_code}&nbsp;</strong>for agreement sign at {companyname}<br /><br />This OTP is valid for 5 minutes only.', '{companyname}', '', 0, 1, 0),
(114, 'contract', 'contract-signed-to-partner', 'english', 'Agreement successfully signed by partner', 'Agreement successfully signed', 'Dear {contact_firstname} {contact_lastname}<br /><br />You successfully signed the agreement at {companyname}<br /><br />Thankyou<br />{companyname}', '{companyname}', '', 0, 1, 0),
(115, 'contract', 'contract-auth-otp-send', 'english', 'Agreement Authentication Email OTP Verification', 'OTP for Agreement Authentication', 'Hi<br /><br />Your one time password (OTP)&nbsp; <strong>{otp_code}&nbsp;</strong>for agreement authentication at {companyname}<br /><br />This OTP is valid for 5 minutes only.', '{companyname}', '', 0, 1, 0),
(116, 'leads', 'lead-customer-office-visit-form-otp-send', 'english', 'Lead customer office visit form otp send', 'OTP For Office Visit Form.', 'Hello, {lead_name}<br /><br />Here is your One time password (OTP) <strong>{otp_code}</strong> to fill visitor form at <strong>{companyname}</strong>', '{companyname}', '', 0, 1, 0),
(117, 'leads', 'lead-customer-office-visitor-form-send', 'english', 'Lead Customer Office Visitor form send', 'Visitor form', '<div><span>Dear </span><span>{lead_name}</span><span>,</span></div>\r\n<br />\r\n<div><span>Please fill-up office visit form.<br /><br /></span><span></span></div>\r\n<div><span>You can access the form through the following link: {visitor_form_link}</span></div>\r\n<div><span>&nbsp; &nbsp; &nbsp; &nbsp; </span></div>\r\n<div><span>Please take a few minutes to fill out the form at your earliest convenience. If you have any questions or require further assistance, please feel free to reach out.</span></div><br /><br />\r\n<div><span>{email_signature}</span></div>\r\n<div></div>', '{companyname}', '', 0, 1, 0),
(118, 'contract', 'send-verified', 'english', 'Agreement Successfully Verified', 'Agreement - {agreement_subject} Successfully Verified', '<p><span style=\"font-size: 12pt;\">Hi&nbsp;{contact_firstname}&nbsp;{contact_lastname}</span><br /><br /><span style=\"font-size: 12pt;\">Your Agreement {agreement_subject} verified successfully.<br /><br />Please find the attached PDF.</span><br /><br /><span style=\"font-size: 12pt;\">Kind Regards,</span><br /><span style=\"font-size: 12pt;\">{email_signature}</span></p>', '{companyname}', '', 0, 1, 0),
(119, 'contract', 'send-contract', 'english', 'Send Agreement to Customer', 'Agreement - {agreement_subject}', '<p><span style=\"font-size: 12pt;\">Hi&nbsp;{contact_firstname}&nbsp;{contact_lastname}</span><br /><br /><span style=\"font-size: 12pt;\">Below is agreement link. please sign it within 24 hours.<br /><br />Agreement Link : {agreement_link}<br /><br /></span><span style=\"font-size: 12pt;\">Looking forward to hear from you.</span><br /><br /><span style=\"font-size: 12pt;\">Kind Regards,</span><br /><span style=\"font-size: 12pt;\">{email_signature}</span></p>', '{companyname}', '', 0, 1, 0),
(120, 'leads', 'lead-new-mail-draft', 'english', 'Lead Customer New Email Draft', '', 'Hello, {lead_name}<br /><br />We have received your request for {product_name}<b></b>. How can we help you?', '{companyname}', '', 0, 1, 0),
(121, 'leads', 'lead-plant-visit-form-otp-send', 'english', 'Lead plant visit form otp send', 'OTP For Plant Visit Form.', 'Hello, {lead_name}<br /><br />Here is your One time password (OTP) <strong>{otp_code}</strong> to fill plant visit form at <strong>{companyname}</strong>', '{companyname}', '', 0, 1, 0),
(122, 'leads', 'lead-plant-visit-form-send', 'english', 'Lead plant visit form send', 'Plant Visit form', '<div><span>Dear </span><span>{lead_name}</span><span>,</span></div>\r\n<br />\r\n<div><span>Please fill-up plant visit form.<br /><br /></span><span></span></div>\r\n<div><span>You can access the form through the following link: {visitor_form_link}</span></div>\r\n<div><span>&nbsp; &nbsp; &nbsp; &nbsp; </span></div>\r\n<div><span>Please take a few minutes to fill out the form at your earliest convenience. If you have any questions or require further assistance, please feel free to reach out.</span></div><br /><br />\r\n<div><span>{email_signature}</span></div>\r\n<div></div>', '{companyname}', '', 0, 1, 0),
(123, 'leads', 'lead-plant-visit-form-approved', 'english', 'Lead plant visit form approved', 'Plant Visit Form Approved', '<div><span>Dear </span><strong>{lead_name}</strong><span>,</span></div>\r\n<br />\r\n<div><span>&nbsp; &nbsp; &nbsp; &nbsp; Your plant visit has been confirmed for <strong>{plant_visit_date_time}</strong> with total number of member <strong>{plant_visit_total_members}</strong>. Total payable amount for your visit is <strong>{plant_visit_payable_amount}</strong>.<br /></span></div>\r\n<div><span>&nbsp; &nbsp; &nbsp; &nbsp;&nbsp;</span></div>\r\n<div><span>{email_signature}<br /></span></div>', '{companyname}', '', 0, 1, 0),
(124, 'leads', 'lead-plant-visit-form-not-approved', 'english', 'Lead plant visit form not approved', 'Plant visit form not approved', '<div>\r\n<div><span>Dear </span><span>{lead_name}</span><span>,</span></div>\r\n<br />\r\n<div><span>&nbsp; &nbsp; &nbsp; &nbsp; Your plant visit form has been not approved due to <strong>{plant_visit_form_not_approved_reason}</strong>. kindly please update the form again using below link.</span></div>\r\n<div><span>&nbsp; &nbsp; &nbsp; &nbsp; </span></div>\r\n<div><span>Form Link : {plant_visit_form_link}</span></div>\r\n<div><span>&nbsp; &nbsp; &nbsp; &nbsp; </span></div>\r\n<div><span>{email_signature}</span></div>\r\n</div>', '{companyname}', '', 0, 1, 0),
(125, 'proposals', 'proposal-advance-payment-recorded', 'english', 'Proposal Advance Payment Recorded (Sent to Customer)', 'Payment Received', '<span style=\"font-size: 12pt;\">Hello <strong>{proposal_customer_name}</strong><br /><br /></span>Thank you for the payment. Find the payment details below:<br /><br />-------------------------------------------------<br /><br />Amount:&nbsp;<strong>{payment_total}<br /></strong>Date:&nbsp;<strong>{payment_date}</strong><br />Proposal number: <span style=\"font-size: 12pt;\"><strong># {proposal_number}<br /><br /></strong></span>-------------------------------------------------<br /><br />We are looking forward working with you.<br /><br /><span style=\"font-size: 12pt;\">Kind Regards,</span><br /><span style=\"font-size: 12pt;\">{email_signature}</span>', '{companyname}', '', 0, 1, 0),
(126, 'contract', 'payment-terms-reminder', 'english', 'Payment Terms Reminder', 'Payment Reminder For Your Agreement - {agreement_subject}', '<p><span style=\"font-size: 12pt;\">Hi {contact_firstname} {contact_lastname}</span><br /><br /><span style=\"font-size: 12pt;\">This is reminder for payment due of your agreement - <strong>{agreement_subject}</strong></span><br /><br /><span style=\"font-size: 12pt;\">Total Term Amount : <strong>{payment_term_amount} ({payment_term_percentage}% Of&nbsp; Total agreement amount)<br /></strong></span><span style=\"font-size: 12pt;\">Total Received Amount for Current Term : <strong><span style=\"color: #339966;\">{payment_term_received_amount}</span><br /></strong></span></p>\r\n<hr />\r\n<p><span style=\"font-size: 12pt;\">Due Amount for current term: <span style=\"color: #ff0000;\"><strong>{payment_term_due_amount}</strong></span></span><br /><span style=\"font-size: 12pt;\">Payment due date for current term : <span style=\"color: #ff0000;\"><strong>{payment_term_due_date}</strong></span></span><br /><br /><span style=\"font-size: 12pt;\">Kind Regards,</span><br /><span style=\"font-size: 12pt;\">{email_signature}</span></p>', '{companyname}', '', 0, 1, 0),
(127, 'contract', 'payment-terms-overdue-notice', 'english', 'Payment Terms Overdue Reminder', 'Payment Overdue Notice For Your Agreement - {agreement_subject}', '<p><span style=\"font-size: 12pt;\">Hi {contact_firstname} {contact_lastname}</span><br /><br /><span style=\"font-size: 12pt;\">This is an overdue notice for your agreement - <strong>{agreement_subject}</strong></span><br /><br /><span style=\"font-size: 12pt;\">Total Term Amount : <strong>{payment_term_amount} ({payment_term_percentage}% Of&nbsp; Total agreement amount)<br /></strong></span><span style=\"font-size: 12pt;\">Total Received Amount for Current Term : <strong><span style=\"color: #339966;\">{payment_term_received_amount}</span><br /></strong></span></p>\n<hr />\n<p><span style=\"font-size: 12pt;\">Due Amount for current term: <span style=\"color: #ff0000;\"><strong>{payment_term_due_amount}</strong></span></span><br /><span style=\"font-size: 12pt;\">Payment due date for current term : <span style=\"color: #ff0000;\"><strong>{payment_term_due_date}</strong></span></span><br /><br /><span style=\"font-size: 12pt;\">Kind Regards,</span><br /><span style=\"font-size: 12pt;\">{email_signature}</span></p>', '{companyname}', '', 0, 1, 0),
(128, 'leads', 'leads-form-brochure-download', 'english', 'Lead Form Brochure Download', '{companyname} - Brochure', '<div>Hello</div>\r\n<div><span><br />Thank you for Contact Us.<br />You can download the Brochure from below link.<br /><br />{company_brochure_link}<br /></span></div>', '{companyname}', '', 0, 1, 0),
(129, 'goals', 'goals-failed-to-achieve', 'english', 'Goal failed to achieve', 'Goal Achievement Update', '<p>Hello <strong>{staff_firstname} {staff_lastname}</strong>,</p>\r\n<p>We regret to inform you that you did not meet the goal set. Below is an overview of your goal progress:</p>\r\n<p><strong>Your Goal Progress Details :</strong></p>\r\n<ul>\r\n<li><strong>Goal Period</strong>: {goal_duration_period}</li>\r\n<li><strong>Goal Target</strong>: {goal_target}</li>\r\n<li><strong>Goal Achieved</strong>: {goal_achievement}</li>\r\n</ul>\r\n<p><strong>Goal Details :</strong></p>\r\n<ul>\r\n<li><strong>Goal Subject</strong>: {goal_subject}</li>\r\n<li><strong>Goal Description</strong>: {goal_description}</li>\r\n<li><strong>Goal Type</strong>: {goal_type}</li>\r\n<li><strong>Goal Duration Type</strong>: {goal_duration_type}</li>\r\n</ul>\r\n<br />We encourage you to try to improve next time, and we believe you will achieve even better results moving forward.', '{companyname}', '', 0, 1, 0),
(130, 'goals', 'goals-achieve', 'english', 'New goal achieved', 'Congratulations on Achieving Your Goal!', '<p>Hello {staff_firstname} {staff_lastname},</p>\r\n<p>We are pleased to inform you that you successfully achieved your goal. Below is a summary of your outstanding performance:</p>\r\n<p><strong>Your Goal Achievement Details</strong></p>\r\n<ul>\r\n<li><strong>Goal Period</strong>: {goal_duration_period}</li>\r\n<li><strong>Goal Target</strong>: {goal_target}</li>\r\n<li><strong>Goal Achieved</strong>: {goal_achievement}</li>\r\n</ul>\r\n<p><strong>Goal Details</strong></p>\r\n<ul>\r\n<li><strong>Goal Subject</strong>: {goal_subject}</li>\r\n<li><strong>Goal Description</strong>: {goal_description}</li>\r\n<li><strong>Goal Type</strong>: {goal_type}</li>\r\n<li><strong>Goal Duration Type</strong>: {goal_duration_type}</li>\r\n</ul>\r\n<p>Congratulations on this achievement! We appreciate your hard work and dedication. Keep up the great work!</p>', '{companyname}', '', 0, 1, 0),
(131, 'goals', 'goals-new-assigned', 'english', 'New goal assigned', 'New goal assigned to you', '<div>Hello <strong>{staff_firstname} {staff_lastname}</strong>,<br /><br />New goal assigned you...<br /><br /><strong>Goal Subject :</strong> {goal_subject} &nbsp; &nbsp; &nbsp; &nbsp;<br /><br /><strong>Goal Description :</strong> {goal_description}<br /><br /><strong>Goal Type :</strong> {goal_subject}<br /><br /><strong>Goal Target : </strong>{goal_target} &nbsp; &nbsp; &nbsp; &nbsp;<br /><br /><strong>Goal Duration : </strong>{goal_duration_type}&nbsp; &nbsp; &nbsp; &nbsp;&nbsp;</div>', '{companyname}', '', 0, 1, 0),
(132, 'contract', 'send-contract-vendor', 'english', 'Send Agreement to Vendor', 'Agreement - {agreement_subject}', '<p><span style=\"font-size: 12pt;\">Hi {vendor_name}</span><br /><br /><span style=\"font-size: 12pt;\">Below is agreement link. please sign it within 24 hours.<br /><br />Agreement Link : {agreement_link}<br /><br /></span><span style=\"font-size: 12pt;\">Looking forward to hear from you.</span><br /><br /><span style=\"font-size: 12pt;\">Kind Regards,</span><br /><span style=\"font-size: 12pt;\">{email_signature}</span></p>', '{companyname}', '', 0, 1, 0),
(133, 'contract', 'contract-signed-to-vendor', 'english', 'Agreement successfully signed by vendor', 'Agreement successfully signed', 'Dear {vendor_name} <br /><br />You successfully signed the agreement at {companyname}<br /><br />Thankyou<br />{companyname}', '{companyname}', '', 0, 1, 0),
(134, 'contract', 'send-verified-vendor', 'english', 'Agreement Successfully Verified (For Vendor)', 'Agreement - {agreement_subject} Successfully Verified', '<p><span style=\"font-size: 12pt;\">Hi&nbsp;{vendor_name}</span><br /><br /><span style=\"font-size: 12pt;\">Your Agreement {agreement_subject} verified successfully.<br /><br />Please find the attached PDF.</span><br /><br /><span style=\"font-size: 12pt;\">Kind Regards,</span><br /><span style=\"font-size: 12pt;\">{email_signature}</span></p>', '{companyname}', '', 0, 1, 0),
(135, 'leads-follow-up', 'leads-follow-up-1', 'english', 'Template 1 : Initial Follow-Up After Inquiry ', '', '', '{companyname}', '', 0, 1, 0),
(136, 'leads-follow-up', 'leads-follow-up-2', 'english', 'Template 2 : Follow-Up After Sending a Proposal/Quotation  ', '', '', '{companyname}', '', 0, 1, 0),
(137, 'leads-follow-up', 'leads-follow-up-3', 'english', 'Template 3 : Follow-Up After No Response ', '', '', '{companyname}', '', 0, 1, 0),
(138, 'leads-follow-up', 'leads-follow-up-4', 'english', 'Template 4 :  Follow-Up After a Meeting or Demo', '', '', '{companyname}', '', 0, 1, 0),
(139, 'leads-follow-up', 'leads-follow-up-5', 'english', 'Template 5 :  Follow-Up on Product Updates or Offers', '', '', '{companyname}', '', 0, 1, 0),
(140, 'leads-follow-up', 'leads-follow-up-6', 'english', 'Template 6 :  Reconnecting After a Long Gap  ', '', '', '{companyname}', '', 0, 1, 0),
(141, 'leads-follow-up', 'leads-follow-up-7', 'english', 'Template 7 :  Request for Additional Information', '', '', '{companyname}', '', 0, 1, 0),
(142, 'leads-follow-up', 'leads-follow-up-8', 'english', 'Template 8 :  Closing Follow-Up  ', '', '', '{companyname}', '', 0, 1, 0),
(143, 'leads-follow-up', 'leads-follow-up-9', 'english', 'Template 9 :  Feedback Request Follow-Up', '', '', '{companyname}', '', 0, 1, 0),
(144, 'leads-follow-up', 'leads-follow-up-default', 'english', 'Default Template : Introduction', '', '', '{companyname}', '', 0, 1, 0),
(145, 'purchase', 'purchase-email-send-to-vendor', 'english', 'Purchase Email Send To Vendor', 'Purchase Order ', '<p data-start=\"165\" data-end=\"184\">Dear <strong>{purchase_to}</strong>,</p>\r\n<p data-start=\"186\" data-end=\"256\">Please find attached the Purchase Order #<strong>{purchase_number}</strong> for your reference.<br /><br /><span>{email_signature}</span></p>', '{companyname}', '', 0, 1, 0),
(146, 'debit_note', 'debit-note-send-to-vendor', 'english', 'Send Debit Note To Email', 'Debit Note With Number #{debit_note_number} Created', 'Dear {vendor_name}<br /><br />We have attached the debit note with number <strong>#{debit_note_number} </strong>for your reference.<br /><br /><strong>Date:</strong>&nbsp;{debit_note_date}<br /><strong>Total Amount:</strong>&nbsp;{debit_note_total}<br /><br /><span style=\"font-size: 12pt;\">Please contact us for more information.</span><br /><br /><span style=\"font-size: 12pt;\">Kind Regards,</span><br /><span style=\"font-size: 12pt;\">{email_signature}</span>', '{companyname}', '', 0, 1, 0),
(147, 'contract', 'send-contract-contact-book-user', 'english', 'Send Agreement to Contact Book User', 'Agreement - {agreement_subject}', '<p><span style=\"font-size: 12pt;\">Hi <strong>{contact_book_firstname} {contact_book_lastname}</strong></span><br /><br /><span style=\"font-size: 12pt;\">Below is agreement link. please sign it within 24 hours.<br /><br />Agreement Link : {agreement_link}<br /><br /></span><span style=\"font-size: 12pt;\">Looking forward to hear from you.</span><br /><br /><span style=\"font-size: 12pt;\">Kind Regards,</span><br /><span style=\"font-size: 12pt;\">{email_signature}</span></p>', '{companyname}', '', 0, 1, 0),
(148, 'contract', 'contract-signed-to-contact-book-user', 'english', 'Agreement successfully signed by Contact Book User', 'Agreement successfully signed', '<span style=\"font-size: 12pt;\">Hi <strong>{contact_book_firstname} {contact_book_lastname}</strong></span><br /><br />You successfully signed the agreement at {companyname}<br /><br />Thankyou<br />{companyname}', '{companyname}', '', 0, 1, 0),
(149, 'contract', 'send-contract-verified-to-contact-book-user', 'english', 'Agreement Successfully Verified (For Contact Book User)', 'Agreement - {agreement_subject} Successfully Verified', '<p><span style=\"font-size: 12pt;\">Hi <strong>{contact_book_firstname} {contact_book_lastname}</strong></span><br /><br /><span style=\"font-size: 12pt;\">Your Agreement {agreement_subject} verified successfully.<br /><br />Please find the attached PDF.</span><br /><br /><span style=\"font-size: 12pt;\">Kind Regards,</span><br /><span style=\"font-size: 12pt;\">{email_signature}</span></p>', '{companyname}', '', 0, 1, 0),
(150, 'contract', 'contract-expiration-to-vendor', 'english', 'Agreement Expiration Reminder (Sent to Vendor)', 'Agreement Expiration Reminder', '<span style=\"font-size: 12pt;\">Dear {vendor_name}</span><br /><br /><span style=\"font-size: 12pt;\">This is a reminder that the following contract will expire soon:</span><br /><br /><span style=\"font-size: 12pt;\"><strong>Subject:</strong> {agreement_subject}</span><br /><span style=\"font-size: 12pt;\"><strong>Description:</strong> {agreement_description}</span><br /><span style=\"font-size: 12pt;\"><strong>Date Start:</strong> {agreement_datestart}</span><br /><span style=\"font-size: 12pt;\"><strong>Date End:</strong> {agreement_dateend}</span><br /><br /><span style=\"font-size: 12pt;\">Please contact us for more information.</span><br /><br /><span style=\"font-size: 12pt;\">Kind Regards,</span><br /><span style=\"font-size: 12pt;\">{email_signature}</span>', '{companyname} | CRM', '', 0, 1, 0),
(151, 'contract', 'contract-expiration-to-contact-book-user', 'english', 'Agreement Expiration Reminder (Sent to Contact Book user)', 'Agreement Expiration Reminder', '<span style=\"font-size: 12pt;\">Dear {contact_book_firstname} {contact_book_lastname}</span><br /><br /><span style=\"font-size: 12pt;\">This is a reminder that the following contract will expire soon:</span><br /><br /><span style=\"font-size: 12pt;\"><strong>Subject:</strong> {agreement_subject}</span><br /><span style=\"font-size: 12pt;\"><strong>Description:</strong> {agreement_description}</span><br /><span style=\"font-size: 12pt;\"><strong>Date Start:</strong> {agreement_datestart}</span><br /><span style=\"font-size: 12pt;\"><strong>Date End:</strong> {agreement_dateend}</span><br /><br /><span style=\"font-size: 12pt;\">Please contact us for more information.</span><br /><br /><span style=\"font-size: 12pt;\">Kind Regards,</span><br /><span style=\"font-size: 12pt;\">{email_signature}</span>', '{companyname} | CRM', '', 0, 1, 0),
(152, 'contract', 'contract-comment-to-vendor', 'english', 'New Comment (Sent to Vendor)', 'New Agreement Comment', 'Dear {vendor_name}<br /><br />A new comment has been made on the following agreement: <strong>{agreement_subject}</strong><br /><br />You can view and reply to the comment on the following link: {agreement_link}<br /><br />Kind Regards,<br />{email_signature}', '{companyname}', '', 0, 1, 0),
(153, 'contract', 'contract-expiration-to-contact-book-user', 'english', 'New Comment (Sent to Contact Book User)', 'New Agreement Comment', 'Dear {contact_book_firstname} {contact_book_lastname}<br /><br />A new comment has been made on the following agreement: <strong>{agreement_subject}</strong><br /><br />You can view and reply to the comment on the following link: {agreement_link}<br /><br />Kind Regards,<br />{email_signature}', '{companyname}', '', 0, 1, 0);
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
