<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitc03c93d6e4d66362f93ad8fb02f0f442
{
    public static $prefixLengthsPsr4 = array (
        'O' => 
        array (
            'OpenCage\\Geocoder\\' => 18,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'OpenCage\\Geocoder\\' => 
        array (
            0 => __DIR__ . '/..' . '/opencage/geocode/src',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitc03c93d6e4d66362f93ad8fb02f0f442::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitc03c93d6e4d66362f93ad8fb02f0f442::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInitc03c93d6e4d66362f93ad8fb02f0f442::$classMap;

        }, null, ClassLoader::class);
    }
}
